const cat = {
  tvAndAudio: "tvAndAudio",
  tvBox: "tvBox",
  powerTools: "powerTools",
  headphones: "headphones",
  cellPhones: "cellPhones",
  smartWatches: "smartWatches",
  gameAndVideo: "gameAndVideo",
  robotClean: "robotClean",
  sportWatches: "sportWatches",
  tablets: "tablets",
  computersAndLaptop: "computersAndLaptop",
  camerasAndPhotos: "camerasAndPhotos",
};
export const categories = [
  {
    _id: 1001,
    name: "TV & Audio",
    image: "https://images-na.ssl-images-amazon.com/images/I/71nkzp07saL.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "tvAndAudio",
  },
  {
    _id: 1002,
    name: "TV Box",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRP8HkbXhZYKy_U9tXkUsxwAob5xR2nLYcVNLHqZLV4xZK8soQQoLrY3sp4NmTidQO5Ri8&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "tvBox",
  },
  {
    _id: 1003,
    name: "Power Tools",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRkqrNlkRERZflq9wLoVCj5syfVfIUBmeilrY-Q2S8-sLf8dsfJUau-flC3-SEu9-FXXnE&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "powerTools",
  },
  {
    _id: 1004,
    name: "Headphones",
    image:
      "https://binhminhdigital.com/storedata/images/product/tai-nghe-sennheiser-hd-430ig.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "headphones",
  },
  {
    _id: 1005,
    name: "Cell Phones",
    image:
      "https://images-na.ssl-images-amazon.com/images/I/71UmvqTuSbL.SS400.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "cellPhones",
  },
  {
    _id: 1006,
    name: "Smart Watches",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTmVQA7datpth-7PP_qHsE3LAOk_5DTdyqS_sDQbECB4QmL83bHNGauA6GTLZA3YbP1qWs&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "smartWatches",
  },
  {
    _id: 1007,
    name: "Game & Video",
    image:
      "https://cdn.tgdd.vn/Products/Images/12918/332756/sony-playstation-5-slim-asia-00479-trang-thumb-600x600.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "gameAndVideo",
  },
  {
    _id: 1008,
    name: "Robot Clean",
    image:
      "https://img4.dhresource.com/webp/m/0x0/f3/albu/jc/s/13/520fc3a1-7706-484f-ad10-f91bff8cb336.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "robotClean",
  },
  {
    _id: 1009,
    name: "Sport Watches",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREJIaiM2xd4qJTdt1FxdVPT-wo_wWJgfwbyTUr0NtNc-bn-s8FpYQazd3zgrjfBcRsfx4&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "sportWatches",
  },
  {
    _id: 1010,
    name: "Tablets",
    image: "https://i.ebayimg.com/images/g/wHEAAOSwmatmpi3Q/s-l1200.jpg",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "tablets",
  },
  {
    _id: 1011,
    name: "Computers & Laptop",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9I-mWyfwNO56O9aDRJurkp_EzrTUEVzFZFfWi77Fhk7JOJ5QZQuNbKIdrHyJzzjUNWs8&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "computersAndLaptop",
  },
  {
    _id: 1012,
    name: "Cameras & Photos",
    image:
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTIjPPQvg-hmz04SUuiHhGTIsSpneUZYu4D6Nd8p9X9yCByuugV5uKb80_3iYpB_8647Gw&usqp=CAU",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore.",
    _base: "camerasAndPhotos",
  },
];

export const highlightsProducts = [
  {
    _id: 3001,
    name: "New Deals at Best Prices",
    title: "From $40.00",
    buttonTitle: "Browse Deals",
    image:
      "https://img.global.news.samsung.com/ph/wp-content/uploads/2025/01/New-Gear-Sale.png",
    _base: "/product",
    color: "#000000",
  },
  {
    _id: 3002,
    name: "Colorful Redmi  Note 6 Pro",
    title: "From $40.00",
    buttonTitle: "Shop Cellphone",
    image: "https://cdn.mos.cms.futurecdn.net/CiXYpwe2788ofHxg9gEi8D.jpg",
    _base: "/category/cellPhones",
    color: "#ffffff",
  },
  {
    _id: 3003,
    name: "1000 mAh Power Bank",
    title: "From $40.00",
    buttonTitle: "Shop Now",
    image:
      "https://choicecollection.in/uploads/main_category/cb01771e522e4e790712a9b7285e42d4.jpg",
    _base: "/product",
    color: "#ffffff",
  },
];

export const blogsData = [
  {
    _id: 4001,
    image: "https://i.ytimg.com/vi/MfCXa-8kkS0/maxresdefault.jpg",
    title: "iPhone 15 rear camera design will be available",
    _base: "Technology",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4002,
    image: "https://topdev.vn/blog/wp-content/uploads/2024/10/AI-Laptop.jpg",
    title: "Setup your surround sound speaker",
    _base: "Samrt thing",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
  {
    _id: 4003,
    image: "https://media.licdn.com/dms/image/v2/D4E12AQEGPt7RVMQ1sQ/article-cover_image-shrink_720_1280/article-cover_image-shrink_720_1280/0/1731314939855?e=2147483647&v=beta&t=YV9oW0tcjdFXFikoSHBXUZxj_IciMP48UjDST7wt5UI",
    title: "Hook up a receiver for your home theater",
    _base: "Life style",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi vitae minus atque ratione. Sequi eos aspernatur delectus officia nemo ipsum facere debitis fugiat eum, quod quia, eligendi nihil sapiente perferendis modi quisquam reiciendis minima esse dolorem, molestias aut? Eum, repudiandae sit ipsum officiis unde reprehenderit inventore odio doloremque recusandae nobis voluptatem ipsa atque, veritatis adipisci reiciendis.",
  },
];

export const products = [
  {
    _id: 2001,
    name: "Divoom Tivoo Portable Bluetooth Speaker Smart Clock Alarm Pixel Art DIY By App LED Light Sign In Decoration Unique Gift",
    images: [
      "https://owlgaming.vn/wp-content/uploads/2024/10/loa-bluetooth-gravastar-mars-pro-black-1.jpg",
      "https://product.hstatic.net/200000807429/product/3_2213b02ca52f4b03a6c024d108f653dd_1024x1024.png",
      "https://level-up.gg/cdn/shop/files/Picture63111.jpg?v=1703925766&width=640",
      "https://smartgatestore.com/wp-content/uploads/2023/08/1-595x595.jpg",
      "https://down-th.img.susercontent.com/file/cn-11134207-7r98o-lnce90fc0uiw76",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.5,
    reviews: 50,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Samsung",
    isStock: true,
    overView: "Blutooth Speaker",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2002,
    name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
    images: [
      "https://down-vn.img.susercontent.com/file/sg-11134201-7rd6v-lwh86os2xfvi6a@resize_w900_nl.webp",
      "https://down-vn.img.susercontent.com/file/sg-11134201-7rd4y-lwh86nl2oe279c@resize_w900_nl.webp",
      "https://down-vn.img.susercontent.com/file/sg-11134201-7rd44-lwh86su0zv7v13@resize_w900_nl.webp",
      "https://down-vn.img.susercontent.com/file/sg-11134201-7rd46-lwh86j4p72dne5.webp",
      "https://down-vn.img.susercontent.com/file/sg-11134201-7rd67-lwh86zy4l3wsc7@resize_w900_nl.webp",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 250,
    discountedPrice: 180,
    quantity: 1,
    rating: 4.8,
    reviews: 80,
    category: "Smart Watches",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Samsung",
    isStock: true,
    overView: "Smart health watch",
    isNew: false,
    _base: cat?.smartWatches,
  },
  {
    _id: 2003,
    name: "Fitness M3 Color Screen Smart Sport Bracelet Activity Running Tracker Heart Rate For Children Men Women Watch For IOS Android",
    images: [
      "https://img.drz.lazcdn.com/static/pk/p/660adf241882ac815160567ffa8a9c85.jpg_720x720q80.jpg",
      "https://i5.walmartimages.com/asr/c8910f97-15ce-4f43-b36e-08de33b8c9af.d8173fcf093e526a946a75cfb082a17a.jpeg?odnHeight=640&odnWidth=640&odnBg=FFFFFF",
      "https://s.alicdn.com/@sc04/kf/Hb70942ef5f73483bb17358a650e9e22f6.jpg_720x720q50.jpg",
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/81/0664083/1.jpg?4114",
      "https://aio.lv/img/cache/product/4331549/11425188_large.webp",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 650,
    discountedPrice: 570,
    quantity: 1,
    rating: 4.2,
    reviews: 30,
    category: "Sport Watches",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "MI Exclusive",
    isStock: true,
    overView: "Smart health watch",
    isNew: true,
    _base: cat?.sportWatches,
  },
  {
    _id: 2004,
    name: "SJ8 Air 1290P 4K 60fps Action Camera WIFI Remote Control Waterproof Sports DV FPV Camera",
    images: [
      "https://www.powerplanetonline.com/cdnassets/sjcam_sj8_plus_001_blanco_l.jpg",
      "https://www.powerplanetonline.com/cdnassets/sjcam_sj8_plus_003_rosa_ad_l.jpg",
      "https://www.powerplanetonline.com/cdnassets/sjcam_sj8_plus_002_negro_ad_l.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 400,
    discountedPrice: 350,
    quantity: 1,
    rating: 4.2,
    reviews: 120,
    category: "Camera & Photos",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: false,
    overView: "Cameras & Photos",
    isNew: false,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 2005,
    name: "Redmi Xiaoai Speaker Play 2.4GHz 1.75 Inch Voice Remote Control Music Player Bluetooth 4.2 Mi Speaker For Android Iphone",
    images: [
      "https://www.batna24.com/img2/1000/333350_161383.webp",
      "https://mrgadgetsolutions.com/wp-content/uploads/2022/02/product_supergear_17_1.jpg",
      "https://www.giztop.com/media/catalog/product/cache/97cc1143d2e20f2b0c8ea91aaa12053c/r/e/redmi_xiaoai_speaker_play.jpg",
      "https://media.karousell.com/media/photos/products/2020/10/6/xiaomi_redmi_xiaoai_speaker_pl_1601992270_c1bdbffa_progressive.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 90,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.2,
    reviews: 20,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Blutooth Speaker",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2006,
    name: "Xiaomi Mi Watch Lite GPS Bluetooth 5.1 Smart Watch Sports Fitness Heart Rate Monitor 1.4 Inch TFTLCD Screen 5 ATM Waterproof Mi Band",
    images: [
      "https://msmobile.vn/images/products/2021/02/25/large/dong-ho-thong-minh-xiaomi-mi-watch-lite-den_1614255003.jpg",
      "https://msmobile.vn/images/products/2021/02/25/large/dong-ho-thong-minh-xiaomi-mi-watch-lite-nga_1614255003.jpg",
      "https://msmobile.vn/images/products/2021/02/25/large/dong-ho-thong-minh-xiaomi-mi-watch-lite-xanh_1614255003.jpg",
      "https://xgsm.pl/hpeciai/2b41e23cf38347720ddeab169b37f32a/pol_pm_Pasek-Silikonowy-do-Xiaomi-Mi-Watch-Lite-Bialy-203525_7.jpg",
      "https://ir.ozone.ru/s3/multimedia-x/wc1000/6585604197.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 300,
    discountedPrice: 280,
    quantity: 1,
    rating: 4.8,
    reviews: 110,
    category: "Smart Watches",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Smart health watch",
    isNew: false,
    _base: cat.smartWatches,
  },
  {
    _id: 2007,
    name: "Kinganda BT513 Foldable Bluetooth Headphones With Mic",
    images: [
      "https://iskamgsm.com/wp-content/uploads/2022/02/product_gear_19_1.jpg",
      "https://iskamgsm.com/wp-content/uploads/2022/02/product_gear_19_4.jpg",
      "https://minimog-4437.kxcdn.com/supergear/wp-content/uploads/sites/2/2022/02/product_gear_19_6-655x655.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 600,
    discountedPrice: 550,
    quantity: 1,
    rating: 4,
    reviews: 60,
    category: "Headphones & Speakers",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Microphones",
    isNew: true,
    _base: cat.headphones,
  },
  {
    _id: 2008,
    name: "New Product Form Lapbook Light Handlift Business Office Game Ben EDP 13.5 In – Black China",
    images: [
      "https://bizweb.dktcdn.net/thumb/large/100/401/951/products/apple-macbook-air-m3-8go-256go-s-9a530460-eb54-4421-a30a-924cc100d7b4.png?v=1729758884067",
      "https://bizweb.dktcdn.net/thumb/large/100/401/951/products/air-m3-15-inch-4-d3e39a76-1bc9-4761-996a-28fa3bc09c5d.png?v=1730034291087",
      "https://bizweb.dktcdn.net/thumb/1024x1024/100/401/951/products/air-m3-15-inch-3.png?v=1730034281900",
      "https://bizweb.dktcdn.net/thumb/large/100/401/951/products/air-m3-15-inch-2.png?v=1730034273117",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 1100,
    discountedPrice: 1080,
    quantity: 1,
    rating: 4.7,
    reviews: 190,
    category: "Computers & Laptops",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Computer Components",
    isNew: false,
    _base: cat?.computersAndLaptop,
  },
  {
    _id: 2009,
    name: "VIOMI V2 Pro LDS Sensor 2 In 1 Sweeping Mopping Robot Wet And Dry Vacuum Cleaner 2100Pa Strong Suction Self-Charging",
    images: [
      "https://cdn.fluidrausa.com/-/media/zodiac/polaris/sliders/products/robotic/p825/fullsize/p825_1.png?rev=b3b601f1ce4f4af787d3c535f80445d0",
      "https://images-na.ssl-images-amazon.com/images/I/81eBXo5hmbL._SL1500_.jpg",
      "https://m.media-amazon.com/images/I/71UrvcN3c5L._AC_SX679_.jpg",
      "https://store.sublue.com/cdn/shop/files/bnpro.jpg?v=1732095069&width=600",
      "https://i5.walmartimages.com/asr/9789e4dc-9139-4673-a1c4-64cd33ebf8d1_1.39dc862462657ecab4fa5d496bdad18c.jpeg?odnWidth=1000&odnHeight=1000&odnBg=ffffff",
      
    ],

    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 450,
    discountedPrice: 380,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: "Robot Clean",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Robot Clean",
    isNew: true,
    _base: cat?.robotClean,
  },
  {
    _id: 2010,
    name: "Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone",
    images: [
      "https://i02.appmifile.com/834_operatorx_operatorx_opx/11/01/2024/2a5eb0f5ac848104898a928f2daa6fdc.png?thumb=1&w=1000&f=webp&q=85",
      "https://i02.appmifile.com/580_operatorx_operatorx_opx/05/06/2024/b6ab95ebbd9fb402b423ba9963522a80.png?thumb=1&w=1000&f=webp&q=85",
      "https://i02.appmifile.com/855_operatorx_operatorx_opx/11/01/2024/4fad3c8039e37a4fa97f8be0462e88e5.png?thumb=1&w=1000&f=webp&q=85",
      "https://i02.appmifile.com/13_operatorx_operatorx_opx/11/01/2024/25da829b5997ff8aea28af388df3b8df.png?thumb=1&w=1000&f=webp&q=85",
      "https://i02.appmifile.com/477_operatorx_operatorx_opx/08/11/2023/a69b2ced4a4e2403fbfd446994c26a06.png?thumb=1&w=1000&f=webp&q=85",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 305,
    discountedPrice: 285,
    quantity: 1,
    rating: 4.1,
    reviews: 160,
    category: "Cell Phones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Cual Sim Phones",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 2011,
    name: "DIDSeth Pan Tilt Security Light Camera Full HD 1080P Wireless Wi-Fi IP Camera Home Dome Surveillance Cameras",
    images: [
      "https://www.dhresource.com/webp/m/0x0/f2/albu/g8/M00/23/61/rBVaVFzoG0uAPYFpAAEwGw33tIM492.jpg",
      "https://ae01.alicdn.com/kf/Secdc1da9bc154d81b00d7ef298273276F.jpg",
      "https://imgaz.staticbg.com/thumb/view/oaupload/banggood/images/D6/30/446f9acd-f988-4646-a5fa-d7b9769fae63.jpg.webp",
      "https://media.takealot.com/covers_images/44fd9bb112504ed4acc1a922d82f92e9/s-pdpxl.file"
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 350,
    discountedPrice: 280,
    quantity: 1,
    rating: 3.8,
    reviews: 250,
    category: "Cameras & Photos",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Security & Protection",
    isNew: true,
    _base: cat?.camerasAndPhotos,
  },
  {
    _id: 2012,
    name: "Electric Hot Melt Glue Gun Cordless Repair DIY Tool Heating Mini Glue Gun With Glue Sticks",
    images: [
      "https://i5.walmartimages.com/seo/UNTIMATY-Cordless-Hot-Glue-Gun-2-0Ah-Battery-Charger-30-Pcs-Full-Size-Sticks-100W-Power-Melt-DIY-Festival-Decor-Gifts_954e10ab-d387-4fc9-861d-39d5d4d25a3a.299a5ab3a0475d99abe9699064bb7594.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
      "https://image.made-in-china.com/202f0j00McqoOlbjiJqk/Hot-Sale-Electric-Silicone-and-High-Quality-Glue-Gun.jpg",
      "https://image.made-in-china.com/318f0j00ktVfujbWHIoZ/FCGG0401-ALI-mp4.webp",
      "https://5.imimg.com/data5/SELLER/Default/2023/9/343475938/DZ/MA/WL/2294379/glue-guns-3680-500x500.jpg",
      "https://s.alicdn.com/@sc04/kf/H9fe31d39f7a4418a92ecc46541588945k.jpg_720x720q50.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 150,
    discountedPrice: 80,
    quantity: 1,
    rating: 4.7,
    reviews: 90,
    category: "Power Tools",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Power Tools",
    isNew: true,
    _base: cat?.powerTools,
  },
  {
    _id: 2013,
    name: "MECOOL KH3 Android 10.0 Smart 4K 60fps TV Box – Black 2GB RAM + 16GB ROM",
    images: [
      "https://img.myipadbox.com/upload/store/product_l/EAT0324AU.jpg",
      "https://images-na.ssl-images-amazon.com/images/I/81Bm67hYcPL.SS400.jpg",
      "https://img.myipadbox.com/upload/store/product_l/EAT0305AU.jpg",
      "https://img.myipadbox.com/upload/store/product_l/EAT0311AU.jpg",
      "https://product.hstatic.net/1000103575/product/mecool-km2-netflix-4k_ebce61708a96437ba8c3f01f6d39ce22.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 210,
    discountedPrice: 200,
    quantity: 1,
    rating: 3.9,
    reviews: 100,
    category: "TV Box",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "TV Box",
    isNew: true,
    _base: cat?.tvBox,
  },
  {
    _id: 2014,
    name: "Sony PS4 Controller Bluetooth Vibration Gamepad For Playstation 4 Detroit Wireless Joystick For PS4 Games Consol",
    images: [
      "https://cdn.onbuy.com/product/65b46efa37f04/500-500/grey-for-sony-ps4-controller-bluetooth-compatible-vibration-gamepad-for-playstation-4-detroit-wireless-joystick-for-ps4slimpropc-games-console.jpg",
      "https://cdn.onbuy.com/product/65b46efd44167/500-500/rose-gold-for-sony-ps4-controller-bluetooth-compatible-vibration-gamepad-for-playstation-4-detroit-wireless-joystick-for-ps4slimpropc-games-console.jpg",
      "https://ng.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/16/0147652/1.jpg?8825",
      "https://s13emagst.akamaized.net/products/63867/63866498/images/res_d92f832f950eb0ba15c369b627e8fee7.jpg",
      "https://m.media-amazon.com/images/I/718rgGDuKjL._AC_UF1000,1000_QL80_.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 80,
    discountedPrice: 75,
    quantity: 1,
    rating: 4.2,
    reviews: 110,
    category: "Game and Video",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Game & Video",
    isNew: true,
    _base: cat?.gameAndVideo,
  },
  {
    _id: 2015,
    name: "GSR 120-Li Hand Drill 12V Lithium Drill Household Power Tool Screwdriver With One Battery – GSR120-LI 1Battery",
    images: [
      "https://tools2weld.in/public/uploads/all/EWF3BIvK6NGpOmetSGqu2KE9qXVg14JXZY3lGvjW.png",
      "https://rukminim2.flixcart.com/image/850/1000/xif0q/power-drill/8/r/8/10-sp-gsr-120-spartan-original-imah5z7utmnjqnht.jpeg?q=90&crop=false",
      "https://m.media-amazon.com/images/I/81VX1o-hodL._AC_UF1000,1000_QL80_.jpg",
      "https://rukminim2.flixcart.com/image/850/1000/xif0q/screw-gun/a/m/z/xdlb-a58-plastic-cordless-12v-electric-battery-powered-original-imagwdhhhgkgbc9f.jpeg?q=90&crop=false",
      "https://cdn.manomano.com/images/images_products/36690278/P/135016586_1.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 560,
    discountedPrice: 400,
    quantity: 1,
    rating: 4,
    reviews: 300,
    category: "Power Tools",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Power Tools",
    isNew: true,
    _base: cat?.powerTools,
  },
  {
    _id: 2016,
    name: "Xiaomi Mi Outdoor Speaker Bluetooth 5.0 IP55 Waterproof Dustproof Portable Wireless Speaker",
    images: [
      "https://ae01.alicdn.com/kf/He11ed119225e4cf9b3bebd658b7bbb5bf.jpg_960x960.jpg",
      "https://m.media-amazon.com/images/I/81XfBikkAkL._AC_UF1000,1000_QL80_.jpg",
      "https://i5.walmartimages.com/seo/Portable-Wireless-Bluetooth-Speaker-strong-Sound-Thunderous-Bass-Bluetooth-Magic-Button-Waterproof-Battery-20-Hours_a54f7fc9-3547-45db-b7c6-d81d906c9607.cb9d04f373367b73fd0de530721812eb.jpeg",
      "https://m.media-amazon.com/images/I/51FnFr42EtL.jpg",
      "https://api-rayashop.freetls.fastly.net/media/catalog/product/cache/4e49ac3a70c0b98a165f3fa6633ffee1/s/p/sp774-6_whyhvo5eb8tsk5la.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 250,
    discountedPrice: 240,
    quantity: 1,
    rating: 4.2,
    reviews: 110,
    category: "TV and Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Blutooth Speakers",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2017,
    name: "Global Version Mi TV Stick Android TV 9.0 Smart 2K HDR 1GB RAM 8GB ROM Bluetooth 4.2 Mini TV Dongle",
    images: [
      "https://shareefcorner.sa/pub/media/catalog/product/mpiowebpcache/82d05cd6abfc8fcfb8bdbf5accf96e1b/x/i/xiaomi_mi_tv_stick_streaming_media_player_pfj4137uk_-_black.webp",
      "https://product.hstatic.net/200000348419/product/r1-bluetooth-presentation-remote-remotes-satechi-206960_ae7e9df10fb64b308fd709dda685a0b7_master.png",
      "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-lxuvozk5kvkrbe",
      "https://down-vn.img.susercontent.com/file/e77545b202db4cd7732aba0e3b03f725",
      "https://down-vn.img.susercontent.com/file/vn-11134207-7r98o-ll96u3402h86ff",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 60,
    discountedPrice: 55,
    quantity: 1,
    rating: 4,
    reviews: 100,
    category: "TV Box",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "TV Box",
    isNew: true,
    _base: cat?.tvBox,
  },
  {
    _id: 2018,
    name: "Xiaomi Mijia LCD Writing Tablet With Pen 10 13.5inch Digital Drawing Message Graphics Electronic Handwriting Pad With Pen",
    images: [
      "https://cdn1.viettelstore.vn/images/Product/ProductImage/medium/iPad-Gen-10-5G-64GB-ble1.jpg",
      "https://cdn.pricebook.co.id/article/60a3a53cb92c2e56658b4567/60a3a53cb92c2e56658b4567_1694425381.jpg",
      "https://m.media-amazon.com/images/I/51tMdGirLpL._AC_UF894,1000_QL80_.jpg",
      "https://cdn.nguyenkimmall.com/images/detailed/850/10054391-ipad-gen-10-wifi-cellular-256gb-mq6w3za-a-hong-3.jpg",
      "https://down-vn.img.susercontent.com/file/sg-11134201-22120-g4xc8uziwlkv60",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 350,
    discountedPrice: 330,
    quantity: 1,
    rating: 4.2,
    reviews: 70,
    category: "Tablets",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Tablets",
    isNew: true,
    _base: cat?.tablets,
  },
  {
    _id: 2019,
    name: "New Creative Cloth Art Home Outdoors Bluetooth Sound Box",
    images: [
      "https://i5.walmartimages.com/asr/2f3ec4fe-4a12-4487-9869-986e0f4e91a2.1f3fad84e873cd073672009d7f16e4a9.jpeg?odnHeight=612&odnWidth=612&odnBg=FFFFFF",
      "https://i5.walmartimages.com/asr/ffdaa394-b52c-473d-bd85-b3f4a483e173.f562c806e551481099beb7c8ed36162f.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
      "https://i.ebayimg.com/images/g/RFQAAOSwUIVnLE95/s-l1200.jpg",
      "https://tribit.com/cdn/shop/products/USPlug.png?v=1710751804&width=1000",
      "https://i5.walmartimages.com/asr/b1725ca4-69b9-4812-8175-b27d55b107eb.c58f10c6324f371d32042d74916a3adc.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 120,
    discountedPrice: 100,
    quantity: 1,
    rating: 4.1,
    reviews: 20,
    category: "Bluetooth Speakers",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Bluetooth Speakers",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2020,
    name: "Global Version Redmi Note 9 Pro 6GB RAM 64GB ROM Smartphone Mobile Phone",
    images: [
      "https://ae01.alicdn.com/kf/S08a0ef54ca80473b9b62739f5c894dfco.jpg",
      "https://i0.wp.com/www.mybdprice.com/wp-content/uploads/2023/08/Xiaomi-Redmi-Note-9-Pro-5G-Mobile-Price-In-Bangladesh-600x600.jpg",
      "https://cdn.tgdd.vn/Products/Images/42/233253/xiaomi-redmi-note-9t-5g-600x600-600x600.jpg",
      "https://auixaysgjr.cloudimg.io/https://cdn.easycash.fr/img/prod/0/0/4/5/5/9/8/8/2/src/6612007-xiaomi-redmi-note-9t-noir-64-go.jpg?ci_sign=eff7788f40dba854b976dc49d1e73c3c6a915ea1",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 450,
    discountedPrice: 410,
    quantity: 1,
    rating: 3.7,
    reviews: 190,
    category: "Cell Phones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Dual Sim Phones",
    isNew: true,
    _base: cat?.cellPhones,
  },
  {
    _id: 2021,
    name: "L21 Bluetooth Earphone Wireless Earbuds 5.0 TWS Headsets Dual Earbuds Bass Sound For Huawei Xiaomi IPhone Samsung Mobile Phones",
    images: [
      "https://down-vn.img.susercontent.com/file/b93db6b07e8ab1cc9a8d6af850ad6536",
      "https://mobilecity-live.s3.ap-southeast-2.amazonaws.com/wp-content/uploads/2021/05/08201738/H9caa212c7e554f27bb9975c694417c471.jpg",
      "https://ke.jumia.is/unsafe/fit-in/500x500/filters:fill(white)/product/11/1378951/1.jpg?9822",
      "https://i5.walmartimages.com/seo/E6s-A6s-E7s-A6r-Y50-Y30-S9-Vg01-V9-F9-Hot-Whosale-Drop-Shipping-Bluetooth-Earphone-Wireless-Headphone-Earbuds-Microphone-Headset-Earphones-amp-Headph_6527abf9-ed28-4844-b364-187ea4983af1.405916809818593dafd25b50c89452bb.jpeg?odnHeight=768&odnWidth=768&odnBg=FFFFFF",
      "https://www.coolpriser.no/images/tvc/C000500100001/6812002240B_1-p.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 350,
    discountedPrice: 320,
    quantity: 1,
    rating: 3.9,
    reviews: 10,
    category: "Headphones",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Fitness Headphones",
    isNew: true,
    _base: cat?.headphones,
  },
  {
    _id: 2022,
    name: "Roborock S7 Robot Vacuum Cleaner For Home Sonic Mopping Ultrasonic Carpet Clean Alexa Mop Lifting Upgrade For S5 Max",
    images: ["https://www.batna24.com/img2/1000/333367_161480.webp",
      "https://reviewindetail.com/wp-content/uploads/sites/3/2021/04/roborock_s7_robot_vacuum_1.jpg",
      "https://www.grover.com/_next/image?url=https%3A%2F%2Fres.cloudinary.com%2Fgrover%2Fimage%2Fupload%2Fe_trim%2Fb_white%2Cc_pad%2Cdpr_2.0%2Ch_500%2Cw_520%2Ff_auto%2Cq_auto%2Fv1628266242%2Ftj2jtp0g8vje2eg5iqee.png&w=3840&q=75",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 250,
    discountedPrice: 240,
    quantity: 1,
    rating: 4.2,
    reviews: 100,
    category: "Robot Clean",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Robot Clean",
    isNew: true,
    _base: cat?.robotClean,
  },
  {
    _id: 2023,
    name: "Klipsch R-120SW Powerful Detailed Home Speaker – Unit",
    images: [
      "https://m.media-amazon.com/images/I/91Ef5beEgqL._AC_UF894,1000_QL80_.jpg",
      "https://www.supersonido.es/productos/imagenes/producto47659.jpg",
      "https://www.adorama.com/images/Large/KPR28PFB.jpg",
      "https://tektul.com/wp-content/uploads/2022/03/product_gear_speaker_1_1.jpg",
      "https://audiojunction.com.au/media/catalog/product/cache/708d3dbcad8ca364acc0a66152853d53/k/l/klipsch-cp-6bf.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 600,
    discountedPrice: 580,
    quantity: 1,
    rating: 4.7,
    reviews: 200,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Bluetooth Speaker",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2024,
    name: "ZY418 Ultra-Thin Sport MP3 MP4 Music Player",
    images: [
      "https://i5.walmartimages.com/seo/ZY-418-Portable-Ultrathin-1-8-Inch-Color-Screen-Sports-MP3-Music-Player-Mini-Plug-Card-Video-MP4Blue_e5e3842e-4b12-4dfe-a707-3ebe1e873a8c.8c775661cc2121646b1d6367d7ce5fea.jpeg",
      "https://m.media-amazon.com/images/I/61Nptq6rXgL._AC_UF894,1000_QL80_.jpg",
      "https://m.media-amazon.com/images/I/61W48vN9HmL.jpg",
      "https://www.agptek.com/wp-content/uploads/2017/10/SMP3GU-1-1000x1000.png",
      "https://m.media-amazon.com/images/I/611IL8wsQsL.jpg",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 80,
    discountedPrice: 70,
    quantity: 1,
    rating: 4.2,
    reviews: 60,
    category: "TV & Audio",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "MP3 Player",
    isNew: true,
    _base: cat?.tvAndAudio,
  },
  {
    _id: 2025,
    name: "Samsung 4K Smart TV UHD Bluetooth 5.2 HDR10+ 55 Inch LED Screen Dolby Audio Wi-Fi AirPlay 2 Voice Assistant Gaming Mode",
    images: [
      "https://m.media-amazon.com/images/I/61yp6r7OsvL.jpg",
      "https://dienmay247.com.vn/wp-content/uploads/2023/05/oled-tivi-4k-samsung-55-inch-55s95b-smart-tv_7ab86bad.webp",
      "https://images.samsung.com/is/image/samsung/p6pim/vn/ua55du7000kxxv/gallery/vn-tvs-ua55du7000kxxv-r-perspective-black-544218847?$684_547_PNG$",
      "https://dienmay247.com.vn/wp-content/uploads/2025/01/4972_tivi_samsung_ua55du8500_2_org.jpg",
      "https://media.flixcar.com/f360cdn/Samsung-184188704-ca-oled-s90d-gaming-qn42s90daexzc-541347791--Download-Source--zoom.png",
    ],
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis repellendus dolore, facilis iste obcaecati ab nesciunt ducimus quidem molestias aut? Aut vitae error delectus itaque facilis obcaecati nemo dolore cumque. Blanditiis minus corrupti dignissimos, voluptas iusto, eligendi maiores doloremque aliquid mollitia in hic dolores pariatur doloribus dolorum totam. Facilis, dignissimos.",
    regularPrice: 220,
    discountedPrice: 210,
    quantity: 1,
    rating: 4.5,
    reviews: 90,
    category: "Smart Watches",
    colors: ["red", "blue", "green", "yellow", "black", "white"],
    brand: "Lorem ipsum dolor sit",
    isStock: true,
    overView: "Smart Health Watch",
    isNew: true,
    _base: cat?.smartWatches,
  },
];
